name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17
    - name: run commands
      run: export GO111MODULE=auto
#     - name: run commands
#       run: go mod init
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
